CREATE TABLE PRODUCTSALES (
    SALEID INT PRIMARY KEY,
    PRODUCTCODE NVARCHAR(20),
    PRODUCTNAME NVARCHAR(100),
    QUANTITY INT,
    UNITPRICE DECIMAL(18, 2),
    SALEDATE DATE
);
GO

INSERT INTO PRODUCTSALES (SALEID, PRODUCTCODE, PRODUCTNAME, QUANTITY, UNITPRICE, SALEDATE)
VALUES
(1, 'P001', 'Pen', 10, 1.50, '2025-06-20'),
(2, 'P001', 'Pen', 5, 1.50, '2025-06-25'),
(3, 'P002', 'Notebook', 3, 3.20, '2025-06-21'),
(4, 'P003', 'Eraser', 15, 0.80, '2025-06-22');
GO

CREATE PROCEDURE sp_GetProductSales
    @StartDate DATE,
    @EndDate DATE,
    @ProductName NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        PRODUCTCODE, 
        PRODUCTNAME, 
        QUANTITY, 
        UNITPRICE, 
        (QUANTITY * UNITPRICE) AS TOTAL, 
        SALEDATE 
    FROM PRODUCTSALES 
    WHERE SALEDATE BETWEEN @StartDate AND @EndDate
    AND (@ProductName IS NULL OR PRODUCTNAME LIKE '%' + @ProductName + '%');
END
GO
